// src/routes/blog/+page.svelte
<script lang="ts">
	import GradientHeader from '../../components/GradientHeader.svelte';
	import Section from '../../components/Section.svelte';
	import { blogPosts } from '../../blogContent/index';
	import { dateToLongString } from '../../utils/timeUtils';
	import Head from '../../components/Head.svelte';
	import { reveal } from '../../utils/reveal';
</script>

<Head title="Blog" />
<Section>
	<GradientHeader title="Blog" />
</Section>
<Section divider />
<Section>
	<div class="py-8" use:reveal>
		<div class="flex flex-col gap-4">
			{#each blogPosts as post (post.slug)}
				<a
					href={`/blog/${post.slug}`}
					class="key-surface group block border border-slate-200 p-5 hover:border-indigo-500 hover:bg-indigo-50 dark:border-slate-800 dark:hover:border-indigo-400 dark:hover:bg-indigo-950/40"
					style="--lift: 4px"
				>
					<div class="flex items-start justify-between gap-4">
						<p class="text-xl font-semibold text-indigo-700 dark:text-indigo-400">
							{post.title}
						</p>
						<span class="key-icon mt-1 icon-[pixelarticons--arrow-right] text-xl" aria-hidden="true"
						></span>
					</div>
					{#if post.subtitle}
						<p class="mt-1 text-lg">
							{post.subtitle}
						</p>
					{/if}
					<div class="mt-3 flex flex-wrap items-center justify-between gap-2">
						<p class="font-mono text-sm text-slate-500 dark:text-slate-400">
							{dateToLongString(post.datePosted)}
						</p>
						<div class="flex items-center gap-1.5">
							{#each post.tags ?? [] as tag (tag)}
								<span class="pixel-tag">
									{tag}
								</span>
							{/each}
						</div>
					</div>
				</a>
			{/each}
		</div>
	</div>
</Section>
<Section divider />

// pages/blog/index.tsx
import React from "react";
import { blogPosts } from "content/blog";
import { Card } from "components/Card";
import { Chip } from "components/Chip";
import { dateToLongString } from "helpers/time-helpers";
import { TechnologyList } from "../../components/TechnologyList";

const Blog: React.FC = () => {
  return (
    <>
      <h1>Blog Posts</h1>
      <span className={"text-lg text-gray-700"}>
        Posts about things I've learned or built
      </span>
      <div className={"px-4 w-full max-w-2xl pb-4"}>
        {blogPosts.map((post, index) => (
          <Card
            key={index}
            className={"w-full mt-6 px-6 py-4"}
            href={"/blog/" + post.meta.url}
          >
            <>
              <h2>{post.meta.title}</h2>
              <span className={"mt-1 text-gray-700 text-lg"}>
                {post.meta.subtitle}
              </span>
              <div
                className={"flex flex-wrap justify-between items-center mt-4"}
              >
                <span className={" text-gray-700 text-md"}>
                  {dateToLongString(post.meta.datePosted)}
                </span>
                {post.meta.tags && (
                  <TechnologyList technologies={post.meta.tags} />
                )}
              </div>
            </>
          </Card>
        ))}
      </div>
    </>
  );
};

export default Blog;
